site_name: BananaBook DOCS
site_description: Documentacion tecnica para la aplicacion web BananaBook
site_author: Rene Guzman

theme:
  name: material
  palette:
    scheme: slate
    primary: yellow
    accent: lime
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.tracking
    - navigation.indexes
    - navigation.search.highlight
    - navigation.search.share
    - navigation.search.suggestions
  language: es
  
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Inicio: index.md
  - Primeros Pasos: getting-started.md
  - API: api.md
