site_name: My Docs
site_description: Documentation for my project
site_author: Rene Guzman

theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: lime
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.tracking
    - navigation.indexes
    - navigation.search.highlight
    - navigation.search.share
    - navigation.search.suggestions
  language: es
  
nav:
  - Home: index.md
  - About: about.md
  - Contact: contact.md
  - Features:
      - Feature 1: features/feature1.md
      - Feature 2: features/feature2.md
      - Feature 3: features/feature3.md
